/**
 * Conservative Japanese labels for USDA's structured English descriptions.
 * This is a navigation aid, not a certified translation. The original remains
 * available by FDC ID, and unknown details are deliberately not invented.
 */

const bases = [
  [/^caribou\b/i, "トナカイ肉"],
  [/^moose\b/i, "ヘラジカ肉"],
  [/^buffalo\b/i, "バイソン肉"],
  [/^bear\b/i, "クマ肉"],
  [/^steelhead trout\b/i, "ニジマス"],
  [/^papaya\b/i, "パパイヤ"],
  [/^nectarine\b/i, "ネクタリン"],
  [/^chokecherries\b/i, "チョークチェリー"],
  [/^prickly pears\b/i, "ウチワサボテンの果実"],
  [/^lime souffle\b/i, "ライムのスフレ"],
  [/^sorbet\b/i, "シャーベット"],
  [/^italian ice\b/i, "イタリアンアイス"],
  [/^snow cone\b/i, "かき氷"],
  [/^popsicle\b|^freezer pop\b/i, "アイスキャンディー"],
  [/^turnover\b/i, "パイ包み"],
  [/^trifle\b/i, "トライフル"],
  [/^firni\b/i, "インド風ライスプディング"],
  [/^barfi or burfi\b/i, "インド風ミルク菓子"],
  [/^haupia\b/i, "ココナッツミルクプリン"],
  [/^yokan\b/i, "ようかん"],
  [/^guava paste\b/i, "グアバペースト"],
  [/^guacamole\b/i, "ワカモレ"],
  [/^chutney\b/i, "チャツネ"],
  [/^chilaquiles\b/i, "チラキレス"],
  [/^frito pie\b/i, "フリトパイ"],
  [/^mexican pizza\b/i, "メキシカンピザ"],
  [/^chiles rellenos\b/i, "チレ・レジェーノ"],
  [/^pita chips\b/i, "ピタチップス"],
  [/^multigrain chips\b/i, "雑穀チップス"],
  [/^chips\b/i, "チップス"],
  [/^croutons\b/i, "クルトン"],
  [/^melba toast\b/i, "メルバトースト"],
  [/^zwieback toast\b/i, "ラスク"],
  [/^oats\b/i, "オーツ麦"],
  [/^noodles\b/i, "麺"],
  [/^spanish rice mix\b/i, "スペイン風ライスミックス"],
  [/^lambsquarters\b/i, "アカザ"],
  [/^prairie turnips\b/i, "プレーリーターニップ"],
  [/^willow\b/i, "ヤナギ"],
  [/^mole sauce\b/i, "モーレソース"],
  [/^white sauce or gravy\b/i, "ホワイトソース・グレービー"],
  [/^black bean sauce\b/i, "黒豆ソース"],
  [/^worcestershire sauce\b/i, "ウスターソース"],
  [/^tomato chili sauce\b/i, "トマトチリソース"],
  [/^tomato sauce\b/i, "トマトソース"],
  [/^hot thai sauce\b/i, "タイ風辛口ソース"],
  [/^barbecue sauce\b/i, "バーベキューソース"],
  [/^buffalo sauce\b/i, "バッファローソース"],
  [/^steak sauce\b/i, "ステーキソース"],
  [/^cocktail sauce\b/i, "カクテルソース"],
  [/^hot pepper sauce\b/i, "ホットペッパーソース"],
  [/^hollandaise sauce\b/i, "オランデーズソース"],
  [/^tartar sauce\b/i, "タルタルソース"],
  [/^horseradish sauce\b/i, "ホースラディッシュソース"],
  [/^pesto sauce\b/i, "ペストソース"],
  [/^fry sauce\b/i, "フライソース"],
  [/^curry sauce\b/i, "カレーソース"],
  [/^soy based sauce\b/i, "大豆ベースのソース"],
  [/^sweet and sour sauce\b/i, "甘酢ソース"],
  [/^lemon-butter sauce\b/i, "レモンバターソース"],
  [/^creamy dressing\b/i, "クリーミードレッシング"],
  [/^honey mustard dip\b/i, "ハニーマスタードのディップ"],
  [/^caramel dip\b/i, "キャラメルディップ"],
  [/^seafood dip\b/i, "魚介のディップ"],
  [/^layer dip\b/i, "層状のディップ"],
  [/^horseradish\b/i, "ホースラディッシュ"],
  [/^wasabi paste\b/i, "わさびペースト"],
  [/^chives\b/i, "チャイブ"],
  [/^cilantro\b/i, "パクチー"],
  [/^parsley\b/i, "パセリ"],
  [/^leeks\b/i, "西洋ねぎ"],
  [/^pimiento\b/i, "ピメント"],
  [/^spearmint\b/i, "スペアミント"],
  [/^sun-dried tomatoes\b/i, "ドライトマト"],
  [/^soy chips\b/i, "大豆チップス"],
  [/^meringues\b/i, "メレンゲ"],
  [/^lard\b/i, "ラード"],
  [/^ghee\b/i, "ギー"],
  [/^animal fat\b/i, "動物性油脂"],
  [/^fat back\b/i, "豚の背脂"],
  [/^table fat\b|^fat\b/i, "油脂"],
  [/^honey butter\b/i, "ハニーバター"],
  [/^honey\b/i, "はちみつ"],
  [/^agave\b/i, "アガベシロップ"],
  [/^molasses\b/i, "糖蜜"],
  [/^simple syrup\b/i, "シュガーシロップ"],
  [/^jelly\b/i, "ゼリー・ジャム"],
  [/^marmalade\b/i, "マーマレード"],
  [/^topping\b/i, "トッピング"],
  [/^icing\b/i, "アイシング"],
  [/^vanilla extract\b/i, "バニラエッセンス"],
  [/^yeast extract spread\b/i, "酵母エキススプレッド"],
  [/^yeast\b/i, "酵母"],
  [/^hard cider\b/i, "ハードサイダー"],
  [/^hard seltzer\b/i, "アルコール入り炭酸水"],
  [/^alcoholic malt beverage\b/i, "麦芽系アルコール飲料"],
  [/^cocktail\b/i, "カクテル"],
  [/^child formula\b/i, "幼児用ミルク"],
  [/^sweet potato\b/i, "さつまいも"],
  [/^applesauce\b/i, "りんごのピューレ"],
  [/^apples?\b/i, "りんご"],
  [/^apricots?\b/i, "あんず"],
  [/^pears?\b/i, "洋なし"],
  [/^peaches?\b/i, "桃"],
  [/^plums?\b/i, "プラム"],
  [/^oranges?\b/i, "オレンジ"],
  [/^grapes?\b/i, "ぶどう"],
  [/^grapefruit\b/i, "グレープフルーツ"],
  [/^figs?\b/i, "いちじく"],
  [/^blackberr/i, "ブラックベリー"],
  [/^cranberr/i, "クランベリー"],
  [/^currants?\b/i, "スグリ"],
  [/^prunes?\b/i, "プルーン"],
  [/^tangerines?\b/i, "みかん"],
  [/^persimmons?\b/i, "柿"],
  [/^rhubarb\b/i, "ルバーブ"],
  [/^plantains?\b/i, "調理用バナナ"],
  [/^fruit cocktail\b/i, "フルーツミックス"],
  [/^lemonade\b/i, "レモネード"],
  [/^lemon juice\b/i, "レモンジュース"],
  [/^lime juice\b/i, "ライムジュース"],
  [/^guava nectar\b/i, "グアバ飲料"],
  [/^green peas\b/i, "グリーンピース"],
  [/^lima beans\b/i, "ライマ豆"],
  [/^pinto beans\b/i, "ピント豆"],
  [/^kidney beans\b/i, "キドニービーンズ"],
  [/^white beans\b/i, "白いんげん豆"],
  [/^black beans\b/i, "黒豆"],
  [/^mung beans\b/i, "緑豆"],
  [/^broadbeans?\b/i, "そら豆"],
  [/^refried beans\b/i, "リフライドビーンズ"],
  [/^baked beans\b/i, "ベイクドビーンズ"],
  [/^chickpeas?\b/i, "ひよこ豆"],
  [/^lentils?\b/i, "レンズ豆"],
  [/^peanuts?\b/i, "ピーナッツ"],
  [/^soybeans?\b/i, "大豆"],
  [/^soy flour\b/i, "大豆粉"],
  [/^soy sauce\b/i, "しょうゆ"],
  [/^cowpeas?\b/i, "ササゲ"],
  [/^collards?\b/i, "コラードグリーン"],
  [/^beets?\b/i, "ビーツ"],
  [/^kale\b/i, "ケール"],
  [/^mustard greens\b/i, "からし菜"],
  [/^turnip greens\b/i, "かぶの葉"],
  [/^turnips?\b/i, "かぶ"],
  [/^summer squash\b/i, "夏カボチャ"],
  [/^pumpkin\b/i, "カボチャ"],
  [/^okra\b/i, "オクラ"],
  [/^seaweed\b/i, "海藻"],
  [/^radishes?\b/i, "ラディッシュ"],
  [/^artichokes?\b/i, "アーティチョーク"],
  [/^snowpeas?\b/i, "さやえんどう"],
  [/^chard\b/i, "フダンソウ"],
  [/^cress\b/i, "クレソン"],
  [/^mixed vegetables\b|^classic mixed vegetables\b/i, "ミックス野菜"],
  [/^balsam-pear\b/i, "ゴーヤ"],
  [/^bologna\b/i, "ボロニアソーセージ"],
  [/^frankfurter\b/i, "フランクフルト"],
  [/^bratwurst\b/i, "ブラートヴルスト"],
  [/^pepperoni\b/i, "ペパロニ"],
  [/^pastrami\b/i, "パストラミ"],
  [/^meat loaf\b/i, "ミートローフ"],
  [/^liver\b/i, "レバー"],
  [/^pate\b/i, "パテ"],
  [/^quail\b/i, "うずら肉"],
  [/^pheasant\b/i, "キジ肉"],
  [/^bison\b/i, "バイソン肉"],
  [/^elk\b/i, "エルク肉"],
  [/^emu\b/i, "エミュー肉"],
  [/^seal\b/i, "アザラシ肉"],
  [/^whale\b/i, "クジラ肉"],
  [/^sea lion\b/i, "アシカ肉"],
  [/^walrus\b/i, "セイウチ肉"],
  [/^quesadilla\b/i, "ケサディーヤ"],
  [/^nachos\b/i, "ナチョス"],
  [/^enchilada\b/i, "エンチラーダ"],
  [/^tamale\b/i, "タマレ"],
  [/^fajita\b/i, "ファヒータ"],
  [/^chimichanga\b/i, "チミチャンガ"],
  [/^taquitos?\b/i, "タキート"],
  [/^gordita\b/i, "ゴルディータ"],
  [/^pupusa\b/i, "ププサ"],
  [/^lasagna\b/i, "ラザニア"],
  [/^ravioli\b/i, "ラビオリ"],
  [/^macaroni or noodles with cheese\b/i, "チーズ入りマカロニ・麺"],
  [/^cocoa powder\b/i, "ココアパウダー"],
  [/^cocoa\b/i, "ココア"],
  [/^custard\b/i, "カスタード"],
  [/^flan\b/i, "フラン"],
  [/^creme brulee\b/i, "クレームブリュレ"],
  [/^mousse\b/i, "ムース"],
  [/^dulce de leche\b/i, "ミルクジャム"],
  [/^shortening\b/i, "ショートニング"],
  [/^breadsticks\b/i, "ブレッドスティック"],
  [/^croissant\b/i, "クロワッサン"],
  [/^pastry\b/i, "ペストリー"],
  [/^frostings?\b/i, "ケーキ用アイシング"],
  [/^nutrition(?:al)? (?:powder|bar)\b|^formulated bar\b/i, "栄養補助食品"],
  [/^frozen novelties\b/i, "冷凍デザート"],
  [/^light ice cream\b/i, "低脂肪アイスクリーム"],
  [/^mixed nuts\b/i, "ミックスナッツ"],
  [/^pecans?\b/i, "ピーカンナッツ"],
  [/^pistachio\b/i, "ピスタチオ"],
  [/^sunflower seeds\b/i, "ひまわりの種"],
  [/^pumpkin seeds\b/i, "かぼちゃの種"],
  [/^chewing gum\b/i, "チューインガム"],
  [/^ketchup\b/i, "ケチャップ"],
  [/^mustard\b/i, "マスタード"],
  [/^garlic\b/i, "にんにく"],
  [/^basil\b/i, "バジル"],
  [/^alfredo sauce\b/i, "アルフレッドソース"],
  [/^ranch dip\b/i, "ランチドレッシングのディップ"],
  [/^chipotle dip\b/i, "チポトレのディップ"],
  [/^tzatziki dip\b/i, "ザジキ"],
  [/^dip\b/i, "ディップ"],
  [/^frozen fruit juice bar\b/i, "果汁アイスバー"],
  [/^frybread\b/i, "揚げパン"],
  [/^liqueur\b/i, "リキュール"],
  [/^rum\b/i, "ラム酒"],
  [/^sangria\b/i, "サングリア"],
  [/^martini\b/i, "マティーニ"],
  [/^(?:mcdonald's|kfc|popeyes|denny's|wendy's|applebee's|subway|digiorno|t\.g\.i\. friday's|on the border|carrabba's|chick-fil-a|domino's|little caesars|hot pockets|papa john's|fast food|school lunch)\b/i, "外食・市販食品"],
  [/^chicken breast\b/i, "鶏むね肉"],
  [/^chicken noodle soup\b/i, "鶏肉の麺スープ"],
  [/^chicken fillet sandwich\b/i, "鶏肉サンド"],
  [/^chicken thigh\b/i, "鶏もも肉"],
  [/^chicken drumstick\b/i, "鶏の骨付きもも肉"],
  [/^chicken wing\b/i, "鶏手羽"],
  [/^chicken or turkey\b/i, "鶏肉・七面鳥"],
  [/^chicken\b/i, "鶏肉"],
  [/^turkey\b/i, "七面鳥"],
  [/^duck\b/i, "鴨肉"],
  [/^goose\b/i, "ガチョウ肉"],
  [/^beef\b/i, "牛肉"],
  [/^veal\b/i, "子牛肉"],
  [/^pork sausage\b/i, "豚肉ソーセージ"],
  [/^pork\b/i, "豚肉"],
  [/^lamb\b/i, "ラム肉"],
  [/^mutton\b/i, "羊肉"],
  [/^game meat\b/i, "ジビエ"],
  [/^venison\b/i, "鹿肉"],
  [/^ostrich\b/i, "ダチョウ肉"],
  [/^bacon\b/i, "ベーコン"],
  [/^ham\b/i, "ハム"],
  [/^sausage\b/i, "ソーセージ"],
  [/^hot dog\b/i, "ホットドッグ"],
  [/^hamburger\b|^burger\b/i, "ハンバーガー"],
  [/^chili\b/i, "チリ料理"],
  [/^meatball/i, "ミートボール"],
  [/^fish,? salmon\b|^salmon\b/i, "サーモン"],
  [/^fish,? tuna\b|^tuna\b/i, "マグロ"],
  [/^fish,? cod\b|^cod\b/i, "タラ"],
  [/^fish,? mackerel\b|^mackerel\b/i, "サバ"],
  [/^fish,? sardine\b|^sardine\b/i, "イワシ"],
  [/^fish,? trout\b|^trout\b/i, "マス"],
  [/^fish,? herring\b|^herring\b/i, "ニシン"],
  [/^fish,? bass\b|^bass\b/i, "スズキ"],
  [/^fish,? eel\b|^eel\b/i, "ウナギ"],
  [/^fish\b/i, "魚"],
  [/^shrimp\b|^prawn\b/i, "海老"],
  [/^crab\b/i, "カニ"],
  [/^lobster\b/i, "ロブスター"],
  [/^clam\b/i, "アサリなどの貝"],
  [/^oyster\b/i, "カキ"],
  [/^mussel\b/i, "ムール貝"],
  [/^scallop\b/i, "ホタテ"],
  [/^squid\b/i, "イカ"],
  [/^octopus\b/i, "タコ"],
  [/^mollusks?\b/i, "貝類"],
  [/^crustaceans?\b/i, "甲殻類"],
  [/^egg\b|^omelet\b/i, "卵料理"],
  [/^tofu\b/i, "豆腐"],
  [/^soybean\b/i, "大豆"],
  [/^edamame\b/i, "枝豆"],
  [/^beans?\b/i, "豆"],
  [/^lentil\b/i, "レンズ豆"],
  [/^chickpea\b/i, "ひよこ豆"],
  [/^peas?\b/i, "えんどう豆"],
  [/^peanut\b/i, "ピーナッツ"],
  [/^nuts?\b/i, "ナッツ"],
  [/^seeds?\b/i, "種子類"],
  [/^wild rice\b/i, "ワイルドライス"],
  [/^rice\b/i, "ごはん・米"],
  [/^oatmeal\b/i, "オートミール"],
  [/^oat\b/i, "オーツ麦"],
  [/^cereals?\b/i, "シリアル"],
  [/^granola\b/i, "グラノーラ"],
  [/^spaghetti with meat sauce\b/i, "ミートソースパスタ"],
  [/^macaroni or pasta salad\b/i, "パスタサラダ"],
  [/^macaroni and cheese\b/i, "マカロニチーズ"],
  [/^tortellini\b/i, "トルテリーニ"],
  [/^pasta\b|^spaghetti\b/i, "パスタ"],
  [/^noodle\b/i, "麺"],
  [/^ramen\b/i, "ラーメン"],
  [/^soba\b/i, "そば"],
  [/^sushi\b/i, "寿司"],
  [/^soup\b/i, "スープ"],
  [/^stew\b/i, "煮込み料理"],
  [/^salad dressing\b/i, "サラダドレッシング"],
  [/^salad\b/i, "サラダ"],
  [/^dressing with\b/i, "詰め物料理"],
  [/^sauce\b/i, "ソース"],
  [/^gravy\b/i, "グレービーソース"],
  [/^pizza\b/i, "ピザ"],
  [/^sandwich\b/i, "サンドイッチ"],
  [/^bread\b/i, "パン"],
  [/^rolls?\b/i, "ロールパン"],
  [/^bagels?\b/i, "ベーグル"],
  [/^muffins?\b/i, "マフィン"],
  [/^pancakes?\b/i, "パンケーキ"],
  [/^waffles?\b/i, "ワッフル"],
  [/^biscuits?\b/i, "ビスケット"],
  [/^french toast\b/i, "フレンチトースト"],
  [/^taco\b/i, "タコス"],
  [/^burrito\b/i, "ブリトー"],
  [/^tortilla\b/i, "トルティーヤ"],
  [/^potato chips\b/i, "ポテトチップス"],
  [/^potatoes, french fried\b/i, "フライドポテト"],
  [/^sweet potatoes?\b/i, "さつまいも"],
  [/^yam\b/i, "ヤムイモ"],
  [/^potato(?:es)?\b/i, "じゃがいも"],
  [/^tomatoes?\b/i, "トマト"],
  [/^carrots?\b/i, "にんじん"],
  [/^broccoli\b/i, "ブロッコリー"],
  [/^spinach\b/i, "ほうれん草"],
  [/^cabbage\b/i, "キャベツ"],
  [/^onions?\b/i, "玉ねぎ"],
  [/^mushrooms?\b/i, "きのこ"],
  [/^corn\b/i, "とうもろこし"],
  [/^peppers?\b/i, "ピーマン・唐辛子類"],
  [/^squash\b/i, "カボチャ類"],
  [/^asparagus\b/i, "アスパラガス"],
  [/^cauliflower\b/i, "カリフラワー"],
  [/^brussels sprouts\b/i, "芽キャベツ"],
  [/^lettuce\b/i, "レタス"],
  [/^cucumber\b/i, "きゅうり"],
  [/^avocado\b/i, "アボカド"],
  [/^vegetable\b/i, "野菜"],
  [/^green beans\b/i, "インゲン豆"],
  [/^taro\b/i, "里芋"],
  [/^celery\b/i, "セロリ"],
  [/^eggplant\b/i, "なす"],
  [/^pickles?\b/i, "漬物"],
  [/^olives?\b/i, "オリーブ"],
  [/^fruit salad\b/i, "フルーツサラダ"],
  [/^fruit juice\b/i, "果汁飲料"],
  [/^fruit\b/i, "果物"],
  [/^apple\b/i, "りんご"],
  [/^banana\b/i, "バナナ"],
  [/^orange\b/i, "オレンジ"],
  [/^grape\b/i, "ぶどう"],
  [/^strawberr/i, "いちご"],
  [/^blueberr/i, "ブルーベリー"],
  [/^raspberr/i, "ラズベリー"],
  [/^cherr/i, "さくらんぼ"],
  [/^pear\b/i, "洋なし"],
  [/^peach\b/i, "桃"],
  [/^plum\b/i, "プラム"],
  [/^pineapple\b/i, "パイナップル"],
  [/^watermelon\b/i, "スイカ"],
  [/^melon\b/i, "メロン"],
  [/^mango\b/i, "マンゴー"],
  [/^milk shake\b|^milkshake\b/i, "ミルクシェイク"],
  [/^buttermilk\b/i, "バターミルク"],
  [/^goat milk\b/i, "ヤギ乳"],
  [/^kefir\b/i, "ケフィア"],
  [/^milk\b/i, "牛乳"],
  [/^yogurt\b/i, "ヨーグルト"],
  [/^cheese\b/i, "チーズ"],
  [/^iced coffee\b/i, "アイスコーヒー"],
  [/^coffee\b/i, "コーヒー"],
  [/^grapefruit juice\b/i, "グレープフルーツジュース"],
  [/^tea\b/i, "お茶"],
  [/^juice\b/i, "ジュース"],
  [/^soft drink\b/i, "清涼飲料水"],
  [/^beverages?\b/i, "飲料"],
  [/^water\b/i, "水"],
  [/^hot chocolate\b/i, "ホットチョコレート"],
  [/^energy drink\b/i, "エナジードリンク"],
  [/^sports drink\b/i, "スポーツ飲料"],
  [/^nutritional drink\b/i, "栄養補助飲料"],
  [/^soymilk\b/i, "豆乳"],
  [/^alcoholic beverage\b/i, "酒類"],
  [/^beer\b/i, "ビール"],
  [/^wine\b/i, "ワイン"],
  [/^oil\b/i, "油"],
  [/^butter\b/i, "バター"],
  [/^margarine\b/i, "マーガリン"],
  [/^cake\b/i, "ケーキ"],
  [/^pie\b/i, "パイ"],
  [/^cookies?\b/i, "クッキー"],
  [/^crackers?\b/i, "クラッカー"],
  [/^puddings?\b/i, "プリン"],
  [/^ice creams?\b/i, "アイスクリーム"],
  [/^candy\b|^candies\b/i, "キャンディー"],
  [/^chocolate\b/i, "チョコレート"],
  [/^doughnuts?\b|^donuts?\b/i, "ドーナツ"],
  [/^popcorn\b/i, "ポップコーン"],
  [/^pretzels?\b/i, "プレッツェル"],
  [/^snacks?\b/i, "スナック菓子"],
  [/^desserts?\b/i, "デザート"],
  [/^cream of wheat\b/i, "小麦のおかゆ"],
  [/^whipped cream substitute\b/i, "ホイップクリーム代替品"],
  [/^cream\b/i, "クリーム"],
  [/^syrups?\b/i, "シロップ"],
  [/^wheat flour\b/i, "小麦粉"],
  [/^whey\b/i, "ホエイ"],
  [/^cornmeal\b/i, "コーンミール"],
  [/^wheat\b/i, "小麦"],
  [/^barley\b/i, "大麦"],
  [/^millet\b/i, "キビ"],
  [/^couscous\b/i, "クスクス"],
  [/^salami\b/i, "サラミ"],
  [/^hummus\b/i, "フムス"],
  [/^almonds?\b/i, "アーモンド"],
  [/^cashews?\b/i, "カシューナッツ"],
  [/^raisins?\b/i, "レーズン"],
  [/^frozen yogurt\b/i, "フローズンヨーグルト"],
  [/^eggnog\b/i, "エッグノッグ"],
  [/^mayonnaise\b/i, "マヨネーズ"],
  [/^salsa\b/i, "サルサソース"],
  [/^vinegar\b/i, "酢"],
  [/^sugar\b/i, "砂糖"],
  [/^sweeteners?\b/i, "甘味料"],
  [/^seasoning\b/i, "調味料"],
  [/^jams?\b|^jellies\b/i, "ジャム"],
  [/^gelatin\b/i, "ゼリー"],
  [/^babyfood\b|^baby food\b|^baby toddler\b|^infant formula\b/i, "乳幼児用食品"],
  [/^raccoon\b/i, "アライグマ肉"],
  [/^toddler formula\b/i, "幼児用ミルク"],
  [/^fast foods\b|^restaurant\b/i, "外食メニュー"],
  [/^spices?\b|^herbs?\b/i, "香辛料・ハーブ"],
];

const details = [
  [/\bwith rice\b/i, "ごはん付き"],
  [/\bfried rice\b/i, "チャーハン"],
  [/\bcurry\b/i, "カレー"],
  [/\bnoodle\b/i, "麺入り"],
  [/\bwith vegetables?\b/i, "野菜入り"],
  [/\bwith cheese\b/i, "チーズ入り"],
  [/\bwith eggs?\b/i, "卵入り"],
  [/\bwith beans?\b/i, "豆入り"],
  [/\bwith meat\b/i, "肉入り"],
  [/\bsalad\b/i, "サラダ"],
  [/\bsandwich\b/i, "サンド"],
  [/\bsoup\b/i, "スープ"],
  [/\bsmoothie\b/i, "スムージー"],
  [/\bjuice\b/i, "ジュース"],
  [/\bwith chocolate\b/i, "チョコレート入り"],
  [/\bwith tomato\b/i, "トマト入り"],
  [/\btomato[ -]?based\b/i, "トマト味"],
  [/\bpotatoes\b/i, "じゃがいも入り"],
  [/\blactose[ -]?free\b/i, "乳糖不使用"],
  [/\bwhole milk\b|\bmilk, whole\b|\bwhole\b/i, "全脂"],
  [/\breduced fat\b/i, "低脂肪"],
  [/\bevapora(?:ted|t)\b/i, "濃縮"],
  [/\bdry\b|\bpowder\b/i, "粉末"],
  [/\borange[ -]?flavo(?:u)?r\b/i, "オレンジ味"],
  [/\bchocolate[ -]?flavo(?:u)?r\b/i, "チョコレート味"],
  [/\bcola\b/i, "コーラ"],
  [/\bwithout sauce\b|\bno sauce\b/i, "ソースなし"],
  [/\bwith sauce\b/i, "ソースあり"],
  [/\bskin not eaten\b|\bskinless\b/i, "皮なし"],
  [/\bskin eaten\b|\bwith skin\b/i, "皮あり"],
  [/\blean and fat\b/i, "赤身・脂身込み"],
  [/\blean only\b|\blean meat\b/i, "赤身"],
  [/\bground\b/i, "ひき肉"],
  [/\btenderloin\b/i, "ヒレ"],
  [/\bsirloin\b/i, "サーロイン"],
  [/\bchuck\b/i, "肩肉"],
  [/\brib\b/i, "リブ"],
  [/\bloin\b/i, "ロース"],
  [/\braw\b/i, "生"],
  [/\bgrilled\b|\bbroiled\b/i, "グリル"],
  [/\broasted\b|\broast\b/i, "ロースト"],
  [/\bbaked\b/i, "オーブン焼き"],
  [/\bstir[ -]?fried\b/i, "炒め"],
  [/\bdeep[ -]?fried\b|\bfried\b/i, "フライ"],
  [/\bsauteed\b/i, "ソテー"],
  [/\bboiled\b/i, "ゆで"],
  [/\bsteamed\b/i, "蒸し"],
  [/\bsmoked\b/i, "燻製"],
  [/\bcanned\b/i, "缶詰"],
  [/\bdried\b/i, "乾燥"],
  [/\bfrozen\b/i, "冷凍"],
  [/\bno added fat\b|\bno fat added\b|\bwithout added fat\b/i, "油脂追加なし"],
  [/\bfat added\b/i, "油脂追加"],
  [/\blow[ -]?fat\b/i, "低脂肪"],
  [/\bnonfat\b|\bfat[ -]?free\b/i, "無脂肪"],
  [/\breduced sodium\b|\blow sodium\b/i, "減塩"],
  [/\bunsalted\b|\bno salt\b/i, "無塩"],
  [/\bsweetened\b/i, "加糖"],
  [/\bunsweetened\b/i, "無糖"],
  [/\brestaurant\b|\bfast food\b/i, "外食"],
  [/\bNFS\b|\bNS as to\b/i, "詳細不明"],
];

const dishTypes = [
  [/\bsalad\b/i, "サラダ"],
  [/\bsandwich\b/i, "サンド"],
  [/\bsoup\b/i, "スープ"],
  [/\bsmoothie\b/i, "スムージー"],
  [/\bjuice\b/i, "ジュース"],
];

const japanesePattern = /[\u3040-\u30ff\u3400-\u9fff]/;

export function foodNameJa(description, category) {
  const source = description.trim();
  const base = bases.find(([pattern]) => pattern.test(source))?.[1]
    ?? (category === "その他" ? "その他の食品" : category);
  const suffix = source.includes(",") ? source.slice(source.indexOf(",") + 1) : source;
  const qualifiers = [...dishTypes.filter(([pattern]) => pattern.test(source)).map(([, label]) => label),
    ...details.filter(([pattern, label]) => pattern.test(suffix)
    && !(label === "フライ" && /\bstir[ -]?fried\b|\bfried rice\b/i.test(suffix))
    && !(label === "全脂" && !/milk|yogurt|cheese|cream/i.test(source))
    && !(label === "じゃがいも入り" && /^potatoes?\b/i.test(source))
    && !(label === "粉末" && /\bdry heat\b/i.test(suffix))
    && !(label === "油脂追加" && /\bno fat added\b/i.test(suffix))).map(([, label]) => label)];
  const uniqueQualifiers = [...new Set(qualifiers)].filter((label) => !base.includes(label)).slice(0, 4);
  const label = uniqueQualifiers.length ? `${base}（${uniqueQualifiers.join("・")}）` : base;
  if (!japanesePattern.test(label)) throw new Error(`Could not localize: ${description}`);
  return label;
}
